# Java异常处理机制概述

当一个新方法被调用时，Java虚拟机会把方法包装成一种叫栈帧的数据结构，然后放入虚拟机栈，当方法执行过程中出现了异常，虚拟机首先查看该方法是否带有处理该异常的代码块，如果有，则执行该代码块，否则弹出该方法，从它的调用者中寻找处理该异常的代码，不停重复，如果异常到最后都还没被处理，那么就会执行以下步骤：

- 调用异常对象的`printStackTrace()`方法，打印来自方法调用栈的异常信息。
- 如果该线程不是主线程，那么终止这个线程，其他线程继续正常运行，否则整个应用程序被终止。



## throws与throw

`throws`表明该方法无法处理这些异常，把异常处理交由它的调用者去负责

```java
public void update(User user)throws SQLException{
    // .....
}
```

`throw`表示在方法内部抛出一个异常

```java
thorw new MyException("出现了异常");
// 抛出的异常对象必须是Throwable类或其子类
```



## 异常处理代码块

```java
try{
    
}catch(SQLExcetion e){
    // 处理异常
}final{
    // 无论是否出现异常都会执行的语句
}
```

# Java异常类

`java.lang.Throwable`类是所有异常类的父类，常用方法有

- `getMessage()`打印异常错误信息
- `printStackTrace()`打印跟踪方法调用栈而获得的详细异常信息

`Throwable`类有两个直接的子类：

- `Error`：表示单靠程序自身无法恢复的严重错误，建议终止程序
- `Exception`：表示程序本身可以处理的异常

## 运行时异常

`RuntimeException`及其子类都是运行时异常，这种异常的特点是Java编译器不会去检查它。

## 受检查异常

除了`RuntimeException`异常，其他Exception都是受检查异常，这中异常的特点是Java编译器会检查它，也就是说，当程序中出现这类异常时，要么用`try-catch`捕获它，要么用`throws`抛出它，否则编译不会通过。

## 两者区别

### 运行时异常与受检查异常

受检查异常表示程序可以处理的异常。

运行时异常表示无法让程序恢复运行的异常。

### 运行时异常与错误

`Error`错误类通常是由Java虚拟机抛出的在JDK中预定义的一些错误类，在编写程序的时候很少继承`Error`。

`RuntimeException`表示程序代码中的错误，开发人员可根据实际需要来扩展它。

## 自定义异常类

可以通过继承`Exception`或`RuntimeException`类来创建自定义的异常。

异常转译：所谓的异常转译就是将一种异常转换另一种新的异常，也许这种新的异常更能准确表达程序发生异常。